FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY app/requirements.api.txt /tmp/requirements.api.txt
RUN pip install --no-cache-dir -r /tmp/requirements.api.txt

COPY app /app/app

CMD ["python", "-m", "app.api"]
