FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# deps
COPY app/requirements.agent.txt /tmp/requirements.agent.txt
RUN pip install --no-cache-dir -r /tmp/requirements.agent.txt

# code
COPY app /app/app

# run
CMD ["python", "-m", "app.agent"]
